[package]
name = "svr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex     = "1"
anyhow    = "1.0"
thiserror = "1"
clap      = { version = "4.4.11", features = ["cargo"]}
chrono    = "0.4"
roxmltree = "0.19"
colored   = "2.1"
